---
name: Make

on:
  schedule:
    - cron:  '0 0 1 * *'
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build on Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        set -xeuo pipefail
        sudo bash -c '
          apt-get update; apt-get -y install lazarus
        ' >/dev/null
        while read -r; do
          if [[ -f "${REPLY%.*}.pas" ]]; then
            if (fpc -Fuuse/mseide-msegui/lib/common/kernel/linux \
                    -Fuuse/mseide-msegui/lib/common/* \
                    -B "${REPLY%.*}.pas"); then
              printf '{}: \x1b[%32mSUCCESS\x1b[0m\n' "${REPLY%.*}.pas"
            else
              printf '{}: \x1b[%32mFAIL\x1b[0m\n'    "${REPLY%.*}.pas"
            fi |
              grep --extended-regexp '(Error:|Fatal:|Linking|exitCode)' |
              tee >&2
          fi
        done < <(find '.' -type 'f' -name '*.prj')
